runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  CLOUD_SQL_CONNECTION_NAME: companysearch-274800:us-central1:company-serach
  DB_USER: postgres
  DB_PASS: atomico123
  DB_NAME: companies
  AUTH_KEY: 'AAAAAAAAAAAAAAAAAAAAAIvtDgEAAAAAC9LMvn7RVmoYDUX2ghHtkZScUB8%3DZrCUPuBpFfoP0FPzDIBJxMt02339TzNnHWIBBHMPnPtsgEUg5n'

beta_settings:
  cloud_sql_instances: companysearch-274800:us-central1:company-serach
